# docker-compose down -v
# docker-compose up -d

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    command: python run.py
    networks:
      - app_network
    environment:
      - DATABASE_URI=mysql+pymysql://user:tsao0120@mysql:3308/takemymoney

  frontend:
    image: nginx:alpine
    volumes:
      - ./app/templates:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/usr/share/nginx/html/static
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tsao0120
      MYSQL_DATABASE: takemymoney
      MYSQL_USER: user
      MYSQL_PASSWORD: tsao0120
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
