"""update releaseat of merch

Revision ID: f70daea83e1f
Revises: e32984785c86
Create Date: 2025-01-05 23:02:27.376984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f70daea83e1f'
down_revision = 'e32984785c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merch', schema=None) as batch_op:
        batch_op.alter_column('release_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('merch', schema=None) as batch_op:
        batch_op.alter_column('release_at',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
