"""add user name to comment

Revision ID: fbf3e61a68d6
Revises: 5f836a23dacd
Create Date: 2025-01-07 02:07:56.807392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf3e61a68d6'
down_revision = '5f836a23dacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))

    with op.batch_alter_table('topic_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_list', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
